### ISSUE TITLE
looks nice, does not play

### ISSUE THREAD

**Issue by makc** [Dobby233Liu/bembedfix#27] opened 2024-07-16 23:28 UTC
https://bembedfix.vercel.app/video/BV1bi421h79s gets me this:
![image](https://github.com/user-attachments/assets/58c15190-762c-4845-8268-75edafe991a9)
but when I click "play" button, nothing happens 😩

**Comment by Dobby233Liu** [comment] 2024-07-17 02:04
Dupe of #26

**Closed** 2024-07-17 02:04 UTC
Labels: duplicate
